#000004

$foreground = rgb(CFDEE4)
$background = rgb(000004)
$wallpaper = rgb(/home/maksi/Pictures/Wallpapers/nixos.png)

$color0 = rgb(000004)
$color1 = rgb(242A36)
$color2 = rgb(262C35)
$color3 = rgb(384E75)
$color4 = rgb(405560)
$color5 = rgb(405B8C)
$color6 = rgb(587A85)
$color7 = rgb(B2C8D0)
$color8 = rgb(7C8C91)
$color9 = rgb(303848)
$color10 = rgb(323B47)
$color11 = rgb(4B689B)
$color12 = rgb(567280)
$color13 = rgb(5579BA)
$color14 = rgb(75A2B1)
$color15 = rgb(B2C8D0)
