#1A191B

$foreground = rgb(F3F0EB)
$background = rgb(1A191B)
$wallpaper = rgb(/home/maksi/Pictures/Wallpapers/mountain-place-2.jpg)

$color0 = rgb(413F42)
$color1 = rgb(36658C)
$color2 = rgb(796E55)
$color3 = rgb(74828A)
$color4 = rgb(A57974)
$color5 = rgb(9E9245)
$color6 = rgb(A79F94)
$color7 = rgb(E6E1DA)
$color8 = rgb(A19E98)
$color9 = rgb(4887BB)
$color10 = rgb(A19371)
$color11 = rgb(9AAEB8)
$color12 = rgb(DCA19B)
$color13 = rgb(D3C35C)
$color14 = rgb(DED4C5)
$color15 = rgb(E6E1DA)
