#141312

$foreground = rgb(FFF8CC)
$background = rgb(141312)
$wallpaper = rgb(/home/maksi/Pictures/Wallpapers/tree.jpg)

$color0 = rgb(3B3A3A)
$color1 = rgb(877A3F)
$color2 = rgb(838888)
$color3 = rgb(BD7C1D)
$color4 = rgb(BEA389)
$color5 = rgb(A0AE91)
$color6 = rgb(BFB052)
$color7 = rgb(F6EDAE)
$color8 = rgb(ADA67A)
$color9 = rgb(B4A354)
$color10 = rgb(AEB5B6)
$color11 = rgb(FCA527)
$color12 = rgb(FDD9B7)
$color13 = rgb(D6E8C1)
$color14 = rgb(FFEB6E)
$color15 = rgb(F6EDAE)
